
function fifo_64to64_ae_block_wrapper_config(this_block)

  % Revision History:
  %
  %   01-Jun-2015  (15:59 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/pcuser/Documents/uWaveMux-mlib-devel/nist_library/fifo/hdl/vhdl/fifo_64to64_ae_block_wrapper.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('fifo_64to64_ae_block_wrapper');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('din');
  this_block.addSimulinkInport('wr_en');
  this_block.addSimulinkInport('rd_en');

  this_block.addSimulinkOutport('dout');
  this_block.addSimulinkOutport('full');
  this_block.addSimulinkOutport('empty');
  this_block.addSimulinkOutport('valid');
  this_block.addSimulinkOutport('prog_empty');

  dout_port = this_block.port('dout');
  dout_port.setType('UFix_64_0');
  full_port = this_block.port('full');
  full_port.setType('UFix_1_0');
  full_port.useHDLVector(false);
  empty_port = this_block.port('empty');
  empty_port.setType('UFix_1_0');
  empty_port.useHDLVector(false);
  valid_port = this_block.port('valid');
  valid_port.setType('UFix_1_0');
  valid_port.useHDLVector(false);
  prog_empty_port = this_block.port('prog_empty');
  prog_empty_port.setType('UFix_1_0');
  prog_empty_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('din').width ~= 64);
      this_block.setError('Input data type for port "din" must have width=64.');
    end

    if (this_block.port('wr_en').width ~= 1);
      this_block.setError('Input data type for port "wr_en" must have width=1.');
    end

    this_block.port('wr_en').useHDLVector(false);

    if (this_block.port('rd_en').width ~= 1);
      this_block.setError('Input data type for port "rd_en" must have width=1.');
    end

    this_block.port('rd_en').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../uWaveMux-mlib-devel/nist_library/fifo/hdl/vhdl/fifo_64to64_ae_block_wrapper.vhd');
  this_block.addFile('../uWaveMux-mlib-devel/nist_library/fifo/hdl/vhdl/fifo_64to64_ae_block.vhd');
  this_block.addFile('../uWaveMux-mlib-devel/nist_library/fifo/hdl/ngc/fifo_64to64_ae_block.ngc');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

