
function data_packetizer_sm_config(this_block)

  % Revision History:
  %
  %   23-Apr-2015  (11:55 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/pcuser/Documents/uWaveMux-mlib-devel/nist_library/data_handler/hdl/vhdl/data_packetizer_sm.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('data_packetizer_sm');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('data_output_en');
  this_block.addSimulinkInport('packet_type');
  this_block.addSimulinkInport('packet_version');
  this_block.addSimulinkInport('channel_count');
  this_block.addSimulinkInport('samples_per_channel');
  this_block.addSimulinkInport('flags');
  this_block.addSimulinkInport('frame_size');
  this_block.addSimulinkInport('data_In_valid');
  this_block.addSimulinkInport('data_In_Empty');
  this_block.addSimulinkInport('data_In');

  this_block.addSimulinkOutport('data_In_Rd_En');
  this_block.addSimulinkOutport('data_Out');
  this_block.addSimulinkOutport('data_Out_Valid');
  this_block.addSimulinkOutport('end_of_Frame');

  data_In_Rd_En_port = this_block.port('data_In_Rd_En');
  data_In_Rd_En_port.setType('UFix_1_0');
  data_In_Rd_En_port.useHDLVector(false);
  data_Out_port = this_block.port('data_Out');
  data_Out_port.setType('UFix_64_0');
  data_Out_Valid_port = this_block.port('data_Out_Valid');
  data_Out_Valid_port.setType('UFix_1_0');
  data_Out_Valid_port.useHDLVector(false);
  end_of_Frame_port = this_block.port('end_of_Frame');
  end_of_Frame_port.setType('UFix_1_0');
  end_of_Frame_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('data_output_en').width ~= 1);
      this_block.setError('Input data type for port "data_output_en" must have width=1.');
    end

    this_block.port('data_output_en').useHDLVector(false);

    if (this_block.port('packet_type').width ~= 8);
      this_block.setError('Input data type for port "packet_type" must have width=8.');
    end

    if (this_block.port('packet_version').width ~= 8);
      this_block.setError('Input data type for port "packet_version" must have width=8.');
    end

    if (this_block.port('channel_count').width ~= 16);
      this_block.setError('Input data type for port "channel_count" must have width=16.');
    end

    if (this_block.port('samples_per_channel').width ~= 16);
      this_block.setError('Input data type for port "samples_per_channel" must have width=16.');
    end

    if (this_block.port('flags').width ~= 16);
      this_block.setError('Input data type for port "flags" must have width=16.');
    end

    if (this_block.port('frame_size').width ~= 16);
      this_block.setError('Input data type for port "frame_size" must have width=16.');
    end

    if (this_block.port('data_In_valid').width ~= 1);
      this_block.setError('Input data type for port "data_In_valid" must have width=1.');
    end

    this_block.port('data_In_valid').useHDLVector(false);

    if (this_block.port('data_In_Empty').width ~= 1);
      this_block.setError('Input data type for port "data_In_Empty" must have width=1.');
    end

    this_block.port('data_In_Empty').useHDLVector(false);

    if (this_block.port('data_In').width ~= 64);
      this_block.setError('Input data type for port "data_In" must have width=64.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../uWaveMux-mlib-devel/nist_library/data_handler/hdl/vhdl/data_packetizer_sm.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

