
function ROACH2_DRAM_SM_config(this_block)

  % Revision History:
  %
  %   27-Mar-2015  (10:04 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/pcuser/Documents/mlib_devel-master/nist_library/dram/ROACH2_DRAM_SM.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('ROACH2_DRAM_SM');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('arm');
  this_block.addSimulinkInport('size');
  this_block.addSimulinkInport('cmd_port');
  this_block.addSimulinkInport('eth_data_in');
  this_block.addSimulinkInport('eth_valid_in');
  this_block.addSimulinkInport('eth_port_in');
  
  this_block.addSimulinkOutport('dram_address_out');
  this_block.addSimulinkOutport('dram_data_out');
  this_block.addSimulinkOutport('dram_read_nwrite_out'); 
  this_block.addSimulinkOutport('dram_cmd_valid_out');
  this_block.addSimulinkOutport('sm_state');
  this_block.addSimulinkOutport('eth_ack_out');  
  
  sm_state_port = this_block.port('sm_state');
  sm_state_port.setType('UFix_1_0');
  sm_state_port.useHDLVector(false);
  eth_ack_out_port = this_block.port('eth_ack_out');
  eth_ack_out_port.setType('UFix_1_0');
  eth_ack_out_port.useHDLVector(false);
  dram_data_out_port = this_block.port('dram_data_out');
  dram_data_out_port.setType('UFix_288_0');
  dram_address_out_port = this_block.port('dram_address_out');
  dram_address_out_port.setType('UFix_32_0');
  dram_read_nwrite_out_port = this_block.port('dram_read_nwrite_out');
  dram_read_nwrite_out_port.setType('UFix_1_0');
  dram_read_nwrite_out_port.useHDLVector(false);
  dram_cmd_valid_out_port = this_block.port('dram_cmd_valid_out');
  dram_cmd_valid_out_port.setType('UFix_1_0');
  dram_cmd_valid_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('arm').width ~= 1);
      this_block.setError('Input data type for port "arm" must have width=1.');
    end

    this_block.port('arm').useHDLVector(false);

    if (this_block.port('size').width ~= 32);
      this_block.setError('Input data type for port "size" must have width=32.');
    end

    if (this_block.port('cmd_port').width ~= 16);
      this_block.setError('Input data type for port "cmd_port" must have width=16.');
    end

    if (this_block.port('eth_data_in').width ~= 64);
      this_block.setError('Input data type for port "eth_data_in" must have width=64.');
    end

    if (this_block.port('eth_valid_in').width ~= 1);
      this_block.setError('Input data type for port "eth_valid_in" must have width=1.');
    end

    this_block.port('eth_valid_in').useHDLVector(false);

    if (this_block.port('eth_port_in').width ~= 16);
      this_block.setError('Input data type for port "eth_port_in" must have width=16.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../uWaveMux-mlib-devel/nist_library/dram/hdl/vhdl/ROACH2_DRAM_SM.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

